### ISSUE TITLE
Count Button 第二次按下不會重新計數

### ISSUE THREAD

**Issue by yusheng0502** [roy860535/glue_soft_project#3]
在我第二次按下Count Button時, CountToTenValue1會增加1, 但是CountToTenValue2不會重新計數, 這樣會顯得CountToTenValue1增加1沒什麼意義

**Comment by roy860535** [comment]
我會製作兩種類型是為了讓他有兩種方法可以到達10，
一個是使用時間，一個是手動點擊，
這樣他就有兩種功能了，手動點擊來增加的功能其實算是順帶，就當作是一個可以計數的功能，
但是以當前情況來看計數器並沒有什麼作用，所以確實蠻沒必要的
所以我會把這個功能拿掉。
