### ISSUE TITLE
Reset Button

### ISSUE THREAD

**Issue by yusheng0502** [roy860535/glue_soft_project#4]
按下Reset Button 時要先勾選 Reset Checkbox才會有效果，這樣的操作方式有點不直觀，想請問這樣的設計的原因為何？有沒有更好的設計方式？

**Comment by roy860535** [comment]
這是一個簡單的防呆機制，
我本來是打算全部都安裝一個專屬的Reset功能，
但考慮到簡易性，所以我使用了更簡短的CheckBox來做為防呆，

那如果說要更好的設計方式，我是直接改成採用MessageBox內部就有的YesNo功能，
來彈出視窗做二次檢查，這功能也是蠻方便的防呆機制。
