### ISSUE TITLE
程式碼重構 - 改善結構

### ISSUE THREAD

**Issue by yusheng0502** [roy860535/glue_soft_project#5]
目前程式的功能及操作介面都已經完善，但是程式碼的結構可以再進一步改善，接下來請試著將程式碼重構。
可以先參考維基百科的重構說明
https://zh.wikipedia.org/zh-tw/%E4%BB%A3%E7%A0%81%E9%87%8D%E6%9E%84

若有問題也可以隨時提出討論

**Comment by roy860535** [comment]
我試著重構了
程式碼重構內容 : 把CountToTen和DisplayTime暫停機制統一使用CancellationTokenSource，取消了bool機制，重複性極高的內容被提取成方法，並且將方法位置重新整理，改善可閱讀性。

**Comment by yusheng0502** [comment]
Count to ten 看起來是這支程式比較複雜的部分, 你可以試著把這個功能及使用到的項目封裝為一個Class嗎？這樣有助於改善程式碼的結構

**Comment by roy860535** [comment]
把Count功能封裝進入一個新的Class中了，Class名為Counter。

**Comment by yusheng0502** [comment]
我們盡量不要把UI元件(Label)傳入邏輯物件(Counter)中，試著讓更新Label這件事留在FormCentralMenu中處理。
> Counter 負責計數
> FormCentralMenu 負責更新UI

**Comment by roy860535** [comment]
我把Counter和DisplayTime分別封裝到了各自的Class之中，並且使用觀察者模式去進行了解偶合，讓數值更新後自動通知UI進行更新，
另外我使用的接口有泛型化，所以可以直接通用於任何單純的數值變化的類型，此兩者使用了相同的接口。

**Comment by yusheng0502** [comment]
使用通知的概念的是正確的方向，但是我希望可以改用Event([event 關鍵字 \- C\# reference \| Microsoft Learn](https://learn.microsoft.com/zh-tw/dotnet/csharp/language-reference/keywords/event))的方式實做，這是比較簡易與簡潔的作法.

**Comment by roy860535** [comment]
OK，我使用Event來代替觀察者了。
